### ISSUE TITLE
About how to obtain VGAMpValue and Variance

### ISSUE THREAD

**Issue by smartpig-666** [April-Secret/DGRNS#3]
Hello, I would like to ask you how the VGAMpValue and Variance in your file GeneOrdering.csv are obtained, are they originally available, or are they calculated by what method. Please explain them for me in detail. Thank you very much

**Comment by MengyuanZhaoo** [comment]
They are originally available from Reference[40] in this paper.

**Comment by smartpig-666** [comment]
Beeline only has pseudo-time information and expression data information, which correspond to ExpressionData.xlsx and PseudoTime.csv of your file. I still don't know where the data in your GeneOrdering.csv file comes from. Can you explain it in detail? Thank you very much
